services:
    # Clúster de Usuarios
    zookeeper-banking:
        image: confluentinc/cp-zookeeper:7.0.1
        restart: always
        container_name: zookeeper-banking
        ports:
            - "2181:2181"
        volumes:
            - zookeeper_data:/var/lib/zookeeper/data
        environment:
            ALLOW_ANONYMOUS_LOGIN: "yes"
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:7.0.1
        container_name: kafka-banking
        depends_on:
            - zookeeper-banking
        restart: always
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-banking:2181
            ALLOW_ANONYMOUS_LOGIN: "yes"
            KAFKA__LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_DEFAULT_REPLICATION_FACTOR: 1
            KAFKA_NUM_PARTITIONS: 2
            KAFKA_LOG_RETENTION_HOURS: 2
        volumes:
            - kafka_data:/etc/kafka
    mysql:
        image: mysql:8.0.25
        container_name: mysql-banking
        restart: always
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: p455w0rd.mysql
            MYSQL_DATABASE: bankingAccount
            MYSQL_USER: banking
            MYSQL_PASSWORD: p455w0rd.banking
        volumes:
            - mysql_data:/var/lib/mysql
    mongodb:
        image: mongo:4.4.6
        container_name: mongodb-banking
        restart: always
        ports:
            - "27017:27017"
        expose:
            - "27017"
        volumes:
            - mongodb_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: r00t
            MONGO_INITDB_ROOT_PASSWORD: p455w0rd.mongo
            MONGO_INITDB_DATABASE: bankingAccount

volumes:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local
    mongodb_data:
        driver: local
    mysql_data:
        driver: local

networks:
    default:
        name: bankingNetwork
